# Generated by Django 5.0 on 2024-01-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fak_owner", "0003_alter_client_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="town_lat",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
