# Generated by Django 5.0 on 2024-01-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fak_owner", "0004_alter_owner_town_lat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="comemnt",
            new_name="comment",
        ),
        migrations.AddField(
            model_name="client",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
