# Generated by Django 5.0 on 2024-01-10 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fak_owner", "0005_rename_comemnt_client_comment_client_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="FakModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fak_number", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "fak_tip",
                    models.CharField(
                        choices=[
                            ("Фактура", "Фактура"),
                            ("Проформа фактура", "Проформа фактура"),
                            ("Кредитно известие", "Кредитно известие"),
                        ],
                        default="Фактура",
                        max_length=32,
                    ),
                ),
                (
                    "suma",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "dds",
                    models.IntegerField(choices=[(0, 0), (9, 9), (20, 20)], default=20),
                ),
                (
                    "cena_netna_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "dds_suma",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "due_date",
                    models.CharField(
                        choices=[
                            ("now", "now"),
                            ("14 days", "14 days"),
                            ("30 days", "30 days"),
                            ("60 days", "60 days"),
                        ],
                        default="now",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CURRENT", "CURRENT"),
                            ("EMAIL_SENT", "EMAIL_SENT"),
                            ("OVERDUE", "OVERDUE"),
                            ("PAID", "PAID"),
                            ("DELETED", "DELETED"),
                        ],
                        default="CURRENT",
                        max_length=32,
                    ),
                ),
                ("poluchena_ot", models.CharField(default="Boris", max_length=52)),
                ("date_sdelka", models.DateField()),
                ("fak_date", models.DateField(auto_now_add=True)),
                ("comment", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "bank",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fak_owner.ownerbank",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="fak_owner.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FakElModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=52)),
                ("kol", models.PositiveIntegerField(default=1)),
                (
                    "dds",
                    models.IntegerField(choices=[(0, 0), (9, 9), (20, 20)], default=20),
                ),
                (
                    "cena_brutna_ed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "cena_netna_ed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "cena_netna_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dds_suma",
                    models.DecimalField(
                        blank=2, decimal_places=2, max_digits=8, null=2
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "fak_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fak_owner.fakmodels",
                    ),
                ),
            ],
        ),
    ]
