# Generated by Django 5.0 on 2024-01-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fak_owner", "0006_fakmodels_fakelmodels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fakmodels",
            name="poluchena_ot",
            field=models.CharField(max_length=52),
        ),
    ]
