# Generated by Django 5.0 on 2024-01-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fak_owner", "0009_rename_fak_date_fakmodels_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fakmodels",
            name="date_created",
            field=models.DateField(blank=True, null=True),
        ),
    ]
