# Generated by Django 5.0 on 2024-01-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fak_owner", "0010_alter_fakmodels_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="fakmodels",
            name="pay_tip",
            field=models.CharField(
                choices=[("Брой", "Брой"), ("Карта", "Карта"), ("Банка", "Банка")],
                default="Брой",
                max_length=32,
            ),
        ),
    ]
