# Generated by Django 5.0 on 2024-01-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fak_owner", "0013_owner_mol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="mol",
            field=models.CharField(max_length=120),
        ),
    ]
