# Generated by Django 5.0 on 2024-02-21 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fak_owner", "0014_alter_owner_mol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ownerbank",
            name="last_fak_number",
        ),
        migrations.RemoveField(
            model_name="ownerbank",
            name="last_pr_number",
        ),
        migrations.AddField(
            model_name="fakmodels",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="fak_owner.owner",
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="last_fak_number",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.AddField(
            model_name="owner",
            name="last_pr_number",
            field=models.CharField(default="0", max_length=10),
        ),
    ]
