# Generated by Django 5.0 on 2024-01-22 20:05

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BedsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("dop_bed", models.BooleanField(default=False)),
                ("age", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FloorsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FoodsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("BB", "BB"),
                            ("HB", "HB"),
                            ("FB", "FB"),
                            ("RO", "RO"),
                        ],
                        default="RO",
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomTypesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("max_people", models.PositiveBigIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name="UslGroupsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoomsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FF0000", image_field=None, max_length=25, samples=None
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="floors",
                        to="hotel_config.floorsmodel",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="types",
                        to="hotel_config.roomtypesmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UslModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "dds",
                    models.CharField(
                        choices=[("0", "0"), ("9", "9"), ("20", "20")],
                        default=0,
                        max_length=2,
                    ),
                ),
                (
                    "group_usl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="usls",
                        to="hotel_config.uslgroupsmodel",
                    ),
                ),
            ],
        ),
    ]
