# Generated by Django 5.0 on 2024-01-22 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel_config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bedsmodel",
            name="usl_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="beds",
                to="hotel_config.uslgroupsmodel",
            ),
        ),
        migrations.AddField(
            model_name="foodsmodel",
            name="usl_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="foods",
                to="hotel_config.uslgroupsmodel",
            ),
        ),
    ]
