# Generated by Django 5.0 on 2024-01-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel_config", "0002_bedsmodel_usl_group_foodsmodel_usl_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floorsmodel",
            name="name",
            field=models.IntegerField(unique=True),
        ),
    ]
