# Generated by Django 5.0 on 2024-02-21 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel_config", "0003_alter_floorsmodel_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bedsmodel",
            options={"ordering": ["dop_bed"]},
        ),
    ]
